import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const text = (path) => readFile(join(root, path), "utf8");

test("Guide tab customization keeps provider identity separate from display metadata", async () => { const [model, groups] = await Promise.all([text("src/core/guideGroupTabModel.ts"), text("src/core/guideGroups.ts")]); assert.match(model, /aliases: Record<string, string>/); assert.match(model, /hidden: string\[\]/); assert.match(model, /order: string\[\]/); assert.match(model, /reverseAliases\[displayName\] \|\| displayName/); assert.match(model, /GUIDE_GROUP_RESERVED_ID/); assert.match(groups, /resolveGuideGroupIdentity\(group\)/); assert.match(groups, /channel\.group === sourceGroup/); });
test("Group settings keep custom visibility on stable ids and provider order on raw ids", async () => { const [screen, persistence] = await Promise.all([text("app/group-settings.tsx"), text("src/core/guideGroupTabPersistence.ts")]); assert.match(screen, /Provider group tabs/); assert.match(screen, /orderedProviderGroups/); assert.match(screen, /tabPrefs\.move\(groupId, -1, providerGroups\)/); assert.match(screen, /tabPrefs\.setVisible\(groupId, !visible\)/); assert.match(screen, /toggleCustomVisible\(group\.id\)/); assert.match(persistence, /const setVisible = useCallback/); });
test("customization persistence cannot let stale initial reads overwrite newer edits", async () => { const files = await Promise.all([text("src/core/guideGroupTabPersistence.ts"), text("src/core/customGuideGroups.ts"), text("src/core/channelCustomize.ts"), text("src/core/guideUiPreferences.ts")]); for (const persistence of files) { assert.match(persistence, /let mutationEpoch = 0/); assert.match(persistence, /const loadEpoch = mutationEpoch/); } });
test("automatic TV layout starts full viewport and calibration owns real overscan", async () => { const layout = await text("src/utils/tvLayout.ts"); const calibration = await text("src/tvCalibration.tsx"); assert.match(layout, /return \{ top: 0, right: 0, bottom: 0, left: 0 \}/); assert.match(calibration, /pathname === "\/player" \|\| pathname\.startsWith\("\/player\/"\)/); });
test("player exposes Fit Fill Zoom Stretch through native PlayerView without decoder restart", async () => { const [adapter, native, screen] = await Promise.all([text("src/components/StreamPlayer.tsx"), text("android/app/src/main/java/com/charmiptv/app/NativePlaybackManager.kt"), text("app/player.tsx")]); assert.match(adapter, /setNativePlaybackResizeMode\(scaleMode\)/); assert.match(native, /fun setResizeMode/); assert.match(native, /AspectRatioFrameLayout\.RESIZE_MODE_ZOOM/); assert.match(native, /AspectRatioFrameLayout\.RESIZE_MODE_FILL/); assert.match(native, /AspectRatioFrameLayout\.RESIZE_MODE_FIT/); assert.match(screen, /type PlayerViewMode = "fit" \| "fill" \| "zoom" \| "stretch"/); });
test("Phase 9 customization screens keep TV focus inside their scroll viewport", async () => { const screens = await Promise.all([text("app/epg-custom.tsx"), text("app/epg-source.tsx"), text("app/group-settings.tsx")]); for (const screen of screens) { assert.match(screen, /FocusGuide/); assert.match(screen, /trapFocusUp/); assert.match(screen, /trapFocusDown/); assert.match(screen, /scrollRef/); assert.match(screen, /nestedScrollEnabled/); } });
