from pathlib import Path

p = Path('frontend/app/epg-custom.tsx')
s = p.read_text(encoding='utf-8')

repls = [
('''    const next = !prefs.primaryEnabled;\n    prefs.setPrimaryEnabled(next);\n    setBusy(true);\n    try {\n      await applyOwnership(next, prefs.userEnabled, prefs.userUrl);\n      setStatus(next ? "Charm built-in EPG enabled." : "Charm built-in EPG disabled. It will no longer be queried or refreshed while off.");''', '''    const next = !prefs.primaryEnabled;\n    setBusy(true);\n    try {\n      await applyOwnership(next, prefs.userEnabled, prefs.userUrl);\n      prefs.setPrimaryEnabled(next);\n      setStatus(next ? "Charm built-in EPG enabled." : "Charm built-in EPG disabled. It will no longer be queried or refreshed while off.");'''),
('''    const url = (prefs.userUrl || urlDraft).trim();\n    prefs.setUserEnabled(next);\n    setBusy(true);\n    try {\n      await applyOwnership(prefs.primaryEnabled, next, url);\n      setStatus(next ? "Custom EPG enabled." : "Custom EPG disabled. Its database remains saved but is no longer queried.");''', '''    const url = (prefs.userUrl || urlDraft).trim();\n    setBusy(true);\n    try {\n      await applyOwnership(prefs.primaryEnabled, next, url);\n      prefs.setUserEnabled(next);\n      setStatus(next ? "Custom EPG enabled." : "Custom EPG disabled. Its database remains saved but is no longer queried.");'''),
('''    setBusy(true);\n    try {\n      prefs.setUserUrl(url);\n      setUrlTouched(false);\n      await applyOwnership(prefs.primaryEnabled, prefs.userEnabled, url);\n      setStatus("Custom EPG URL saved.");''', '''    setBusy(true);\n    try {\n      await applyOwnership(prefs.primaryEnabled, prefs.userEnabled, url);\n      prefs.setUserUrl(url);\n      setUrlTouched(false);\n      setStatus("Custom EPG URL saved.");'''),
('''      prefs.setUserUrl(url);\n      if (!prefs.userEnabled) prefs.setUserEnabled(true);\n      await configureNativeGuideOwnership(prefs.primaryEnabled, true, url, prefs.userOverrides);\n      const result = await refreshNativeUserGuide(url);''', '''      await configureNativeGuideOwnership(prefs.primaryEnabled, true, url, prefs.userOverrides);\n      prefs.setUserUrl(url);\n      if (!prefs.userEnabled) prefs.setUserEnabled(true);\n      const result = await refreshNativeUserGuide(url);'''),
('''      const overrides = { ...prefs.userOverrides, [channel.id]: xmltvId };\n      prefs.setUserOverride(channel.id, xmltvId);\n      await setNativeGuideChannelBinding(channel.id, xmltvId);\n      await configureNativeGuideOwnership(\n        prefs.primaryEnabled,\n        prefs.userEnabled,\n        prefs.userUrl,\n        overrides,\n      );\n      invalidateGuideOwnershipCaches();''', '''      const previous = prefs.userOverrides[channel.id] || null;\n      const overrides = { ...prefs.userOverrides, [channel.id]: xmltvId };\n      await setNativeGuideChannelBinding(channel.id, xmltvId);\n      try {\n        await configureNativeGuideOwnership(\n          prefs.primaryEnabled,\n          prefs.userEnabled,\n          prefs.userUrl,\n          overrides,\n        );\n      } catch (error) {\n        await setNativeGuideChannelBinding(channel.id, previous).catch(() => undefined);\n        throw error;\n      }\n      prefs.setUserOverride(channel.id, xmltvId);\n      invalidateGuideOwnershipCaches();'''),
('''      const overrides = { ...prefs.userOverrides };\n      delete overrides[channel.id];\n      prefs.setUserOverride(channel.id, null);\n      await setNativeGuideChannelBinding(channel.id, null);\n      await configureNativeGuideOwnership(\n        prefs.primaryEnabled,\n        prefs.userEnabled,\n        prefs.userUrl,\n        overrides,\n      );\n      invalidateGuideOwnershipCaches();''', '''      const previous = prefs.userOverrides[channel.id] || null;\n      const overrides = { ...prefs.userOverrides };\n      delete overrides[channel.id];\n      await setNativeGuideChannelBinding(channel.id, null);\n      try {\n        await configureNativeGuideOwnership(\n          prefs.primaryEnabled,\n          prefs.userEnabled,\n          prefs.userUrl,\n          overrides,\n        );\n      } catch (error) {\n        await setNativeGuideChannelBinding(channel.id, previous).catch(() => undefined);\n        throw error;\n      }\n      prefs.setUserOverride(channel.id, null);\n      invalidateGuideOwnershipCaches();'''),
]

for old, new in repls:
    if old not in s:
        raise SystemExit('guard failed: expected custom EPG transaction block not found')
    s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8')
