from pathlib import Path

path = Path('frontend/src/components/PurpleTvShell.tsx')
text = path.read_text(encoding='utf-8')
old = '''  const reopenArmedAtRef = useRef(0);\n  useFocusEffect(\n    useCallback(() => {\n      if (Platform.OS === "web") return;\n      const sub = BackHandler.addEventListener("hardwareBackPress", () => {\n        if (active === "/guide" && !drawerOpen && !activeProgram) {\n          // PurpleGuideScreen owns closed-guide Back so it can enter the\n          // dedicated Groups drawer first. Never skip directly to main nav.\n          reopenArmedAtRef.current = 0;\n          return false;\n        }\n        const decision = evaluateDrawerBack({\n          drawerOpen,\n          blockingOverlayOpen: !!activeProgram,\n          reopenArmedAt: reopenArmedAtRef.current,\n        });\n        if (decision === "pass-through") {\n          reopenArmedAtRef.current = 0;\n          return false;\n        }\n        if (decision === "arm-reopen") {\n          reopenArmedAtRef.current = Date.now();\n          return true;\n        }\n        if (decision === "open-drawer") {\n          reopenArmedAtRef.current = 0;\n          openDrawer();\n          return true;\n        }\n        if (decision === "close-drawer") {\n          reopenArmedAtRef.current = 0;\n          closeDrawer();\n          return true;\n        }\n        return true;\n      });\n      return () => sub.remove();\n    }, [active, activeProgram, closeDrawer, drawerOpen, openDrawer]),\n  );\n'''
new = '''  useFocusEffect(\n    useCallback(() => {\n      if (Platform.OS === "web") return;\n      const sub = BackHandler.addEventListener("hardwareBackPress", () => {\n        if (active === "/guide" && !drawerOpen && !activeProgram) {\n          // Guide owns closed-guide Back so it can enter the dedicated Groups\n          // drawer first. The shell never opens a closed drawer from Back.\n          return false;\n        }\n        const decision = evaluateDrawerBack({\n          drawerOpen,\n          blockingOverlayOpen: !!activeProgram,\n        });\n        if (decision === "pass-through") return false;\n        if (decision === "close-drawer") {\n          closeDrawer();\n          return true;\n        }\n        return false;\n      });\n      return () => sub.remove();\n    }, [active, activeProgram, closeDrawer, drawerOpen]),\n  );\n'''
if old not in text:
    raise SystemExit('expected old drawer Back block not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
